# Generated by Django 3.0.2 on 2020-01-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0007_auto_20200122_1503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Image',
        ),
    ]
