# Generated by Django 3.0.2 on 2020-01-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0008_auto_20200122_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='hotel_Main_Img',
        ),
        migrations.AddField(
            model_name='image',
            name='converted_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='original_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
