# Generated by Django 3.0.2 on 2020-01-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0009_auto_20200122_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='converted_img',
            field=models.ImageField(null=True, upload_to='converted/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='original_img',
            field=models.ImageField(null=True, upload_to='original/'),
        ),
    ]
