# Generated by Django 3.0.2 on 2020-01-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0010_auto_20200122_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
