# Generated by Django 3.0.2 on 2020-01-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0011_auto_20200122_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
    ]
