# Generated by Django 3.0.2 on 2020-01-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0012_auto_20200122_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='converted_size',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='original_size',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='quality',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
